apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "cdp-impala-provisioner.labels" . | nindent 4 }}
  name: {{ template "cdp-impala-provisioner.fullname" . }}-config
data:
  application.conf: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.conf" | nindent 4 }}
  {{ end }}
  logback.xml: |
  {{- if .Values.logbackOverride -}}
  {{- .Values.logbackOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/logback.xml" | nindent 4 }}
  {{ end }}
  {{- if .Values.kerberos.enabled }}
  krb5.conf: |
  {{- if .Values.kerberos.krb5Override -}}
  {{- .Values.kerberos.krb5Override | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/krb5.conf" | nindent 4 }}
  {{ end }}
  jaas.conf: |
  {{- if .Values.kerberos.jaasOverride -}}
  {{- .Values.kerberos.jaasOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/jaas.conf" | nindent 4 }}
  {{ end }}
  {{- end }}