package it.agilelab.provisioning.impala.table.provisioner.gateway.ranger

import it.agilelab.provisioning.commons.client.ranger.model._
import it.agilelab.provisioning.impala.table.provisioner.gateway.ranger.policy.RangerPolicyGenerator
import org.scalatest.funsuite.AnyFunSuite

class RangerPolicyGeneratorTest extends AnyFunSuite {

  test("impalaTable") {
    val actual = RangerPolicyGenerator.impalaTable(
      database = "db",
      table = "tbl",
      owners = Seq("owner"),
      users = Seq("usr1", "usr2"),
      usersOwners = Seq("x"),
      "zzz"
    )
    val expected = RangerPolicy(
      id = -1,
      service = "cm_hive",
      name = "db_tbl_access_policy",
      description = "db_tbl_access_policy",
      isAuditEnabled = true,
      isEnabled = true,
      resources = RangerResources.table("db", "tbl"),
      policyItems = Seq(
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("owner"),
          users = Seq("x"),
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.all
          )
        ),
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("usr1", "usr2"),
          users = Seq.empty[String],
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.select,
            Access.read
          )
        )
      ),
      serviceType = "hive",
      policyLabels = Seq("autogenerated"),
      isDenyAllElse = true,
      "zzz",
      0
    )

    assert(actual == expected)
  }

  test("impalaTable without users") {
    val actual = RangerPolicyGenerator.impalaTable(
      database = "db",
      table = "tbl",
      owners = Seq("owner"),
      users = Seq.empty,
      usersOwners = Seq("xy"),
      "zzz"
    )
    val expected = RangerPolicy(
      id = -1,
      service = "cm_hive",
      name = "db_tbl_access_policy",
      description = "db_tbl_access_policy",
      isAuditEnabled = true,
      isEnabled = true,
      resources = RangerResources.table("db", "tbl"),
      policyItems = Seq(
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("owner"),
          users = Seq("xy"),
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.all
          )
        )
      ),
      serviceType = "hive",
      policyLabels = Seq("autogenerated"),
      isDenyAllElse = true,
      "zzz",
      0
    )
    assert(actual == expected)
  }

  test("impalaTable with default userOwners") {
    val actual = RangerPolicyGenerator.impalaTable(
      database = "db",
      table = "tbl",
      owners = Seq("owner"),
      users = Seq.empty,
      usersOwners = Seq("x", "y"),
      "zzz"
    )
    val expected = RangerPolicy(
      id = -1,
      service = "cm_hive",
      name = "db_tbl_access_policy",
      description = "db_tbl_access_policy",
      isAuditEnabled = true,
      isEnabled = true,
      resources = RangerResources.table("db", "tbl"),
      policyItems = Seq(
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("owner"),
          users = Seq("x", "y"),
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.all
          )
        )
      ),
      serviceType = "hive",
      policyLabels = Seq("autogenerated"),
      isDenyAllElse = true,
      "zzz",
      0
    )

    assert(actual == expected)
  }

  test("impalaDb") {
    val actual = RangerPolicyGenerator.impalaDb(
      database = "db",
      owners = Seq("owner"),
      users = Seq("usr"),
      usersOwners = Seq("x", "y"),
      "zzz"
    )
    val expected = RangerPolicy(
      -1,
      service = "cm_hive",
      name = "db_access_policy",
      description = "db_access_policy",
      isAuditEnabled = true,
      isEnabled = true,
      resources = Map(
        "database" -> RangerResource(Seq("db"), isExcludes = false, isRecursive = false)
      ),
      policyItems = Seq(
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("owner"),
          users = Seq("x", "y"),
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.all
          )
        ),
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("usr"),
          users = Seq.empty,
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.select
          )
        )
      ),
      serviceType = "hive",
      policyLabels = Seq("autogenerated"),
      isDenyAllElse = true,
      "zzz",
      1
    )
    assert(actual == expected)
  }

  test("impalaUrl") {
    val actual = RangerPolicyGenerator.impalaUrl(
      database = "db",
      table = "tbl",
      url = "url",
      owners = Seq("owner"),
      users = Seq("usr"),
      usersOwners = Seq("x", "y"),
      "zzz"
    )
    val expected = RangerPolicy(
      -1,
      service = "cm_hive",
      name = "db_tbl_url_access_policy",
      description = "db_tbl_url_access_policy",
      isAuditEnabled = true,
      isEnabled = true,
      resources = Map(
        "url" -> RangerResource(Seq("url"), isExcludes = false, isRecursive = true)
      ),
      policyItems = Seq(
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("owner"),
          users = Seq("x", "y"),
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.all
          )
        ),
        RangerPolicyItem(
          roles = Seq.empty[String],
          groups = Seq("usr"),
          users = Seq.empty,
          conditions = Seq.empty[String],
          delegateAdmin = false,
          accesses = Seq(
            Access.select,
            Access.read
          )
        )
      ),
      serviceType = "hive",
      policyLabels = Seq("autogenerated"),
      isDenyAllElse = true,
      "zzz",
      0
    )
    assert(actual == expected)
  }
}
